# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: fhir.who.smart-ig-starter-kit
canonical: http://worldhealthorganization.github.io/smart-ig-starter-kit
name: smart-ig-starter-kit
status: draft
version: 0.2.1
fhirVersion: 4.0.1
date: 2021-06-03
# copyright:
copyrightYear: 2021+
releaseLabel: "CI Build"
title: "WHO SMART Guideline: Starter Kit"
description: "SMART Guidelines Implementation Guide starter kit"
license: CC0-1.0

pages: 
  home.md:
    title: "Home"
    overview.md:
      title: "Overview"
    assumptions.md:
     title: "Assumptions"
  authoring_overview.md:
    title: "Authoring"
    structure.md:
      title: "Structure of the SOP IG"
    naming_conventions.md:
      title: "Naming Conventions"
    content_types.md:
      title: "Types of Content"
    l2_overview.md:
      title: "L2 overview"
    authoring_artifacts.md:
      title: "Authoring Artifacts"
      l3_personas.md:
        title: "Personas"
      l3_logicalmodels.md:
        title: "Logical Models"
    ig_licensing.md:
      title: "Licensing"
    versioning.md:
      title: "Versioning"
  ig_setup.md:
    title: "IG Setup"
    github_setup.md:
      title: "Github Initialization"
    ig_configuration.md:
      title: "IG Configuration"
    folder_structure.md:
      title: "Folders and File Structure"
  validating_ig.md:
    title: "Validating IG"
    qa_check.md:
      title: "QA check"
  indices.md:
    title: "Indices"
publisher:
  name: WHO
  url: http://who.int
email: leitnerc@who.int
# contact:
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001
# experimental: true
dependencies:
